"""adding column in package table

Revision ID: 14a4f1f72e4d
Revises: 3e90ac33a2ec
Create Date: 2025-11-12 15:35:06.348685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a4f1f72e4d'
down_revision = '3e90ac33a2ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catalog_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('activated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'packagecatalog', ['catalog_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payments_package'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'packagecatalog', ['package_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_payments_package'), 'packagecatalog', ['package_id'], ['id'])

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('activated_at')
        batch_op.drop_column('catalog_id')

    # ### end Alembic commands ###
