"""add created_at column in payments table

Revision ID: 24b7cb2d6cf8
Revises: f02f40918248
Create Date: 2025-11-15 18:03:47.959660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b7cb2d6cf8'
down_revision = 'f02f40918248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('actual_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('available_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('referral_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_users_referral_code'))
        batch_op.create_unique_constraint(None, ['referral_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_users_referral_code'), ['referral_code'], unique=True)
        batch_op.alter_column('referral_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('available_balance',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('actual_balance',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
