"""add indixes on users, wallet, and transaction

Revision ID: 2aea518b2769
Revises: 4dc93a4490c8
Create Date: 2025-11-25 17:56:46.779129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aea518b2769'
down_revision = '4dc93a4490c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_user_phone', ['phone'], unique=False)
        batch_op.create_index('idx_user_referral_code', ['referral_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_user_referral_code')
        batch_op.drop_index('idx_user_phone')

    # ### end Alembic commands ###
