"""Rename package_id to package_catalog_id in payments

Revision ID: 3012212cc264
Revises: 14a4f1f72e4d
Create Date: 2025-11-13 01:06:30.609164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3012212cc264'
down_revision = '14a4f1f72e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_catalog_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('payments_package_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'packagecatalog', ['package_catalog_id'], ['id'])
        batch_op.drop_column('package_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payments_package_id_fkey'), 'packagecatalog', ['package_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('package_catalog_id')

    # ### end Alembic commands ###
