"""Sync with manual changes

Revision ID: 3e90ac33a2ec
Revises: e3b1b72a7ede
Create Date: 2025-11-11 18:02:18.836646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e90ac33a2ec'
down_revision = 'e3b1b72a7ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packagecatalog', schema=None) as batch_op:
        batch_op.alter_column('features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('transaction_type')

    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('withdrawals_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('reference')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('withdrawals_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('packagecatalog', schema=None) as batch_op:
        batch_op.alter_column('features',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###
