"""add security_hash and other updates

Revision ID: 4d60f24f5a3b
Revises: 24b7cb2d6cf8
Create Date: 2025-11-16 14:53:44.426582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d60f24f5a3b'
down_revision = '24b7cb2d6cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral_bonuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_hash', sa.String(length=128), nullable=False))
        batch_op.create_index(batch_op.f('ix_referral_bonuses_security_hash'), ['security_hash'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('actual_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('available_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('referral_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_users_referral_code'))
        batch_op.create_unique_constraint(None, ['referral_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_users_referral_code'), ['referral_code'], unique=True)
        batch_op.alter_column('referral_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('available_balance',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('actual_balance',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))

    with op.batch_alter_table('referral_bonuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referral_bonuses_security_hash'))
        batch_op.drop_column('security_hash')

    # ### end Alembic commands ###
