"""updates for version 5.0.0

Revision ID: 4dc93a4490c8
Revises: 8d80e876962e
Create Date: 2025-11-23 07:28:44.180899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc93a4490c8'
down_revision = '8d80e876962e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.alter_column('external_ref',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_withdrawals_external_ref'))
        batch_op.create_index(batch_op.f('ix_withdrawals_external_ref'), ['external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_withdrawals_net_amount'), ['net_amount'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_withdrawals_net_amount'))
        batch_op.drop_index(batch_op.f('ix_withdrawals_external_ref'))
        batch_op.create_index(batch_op.f('idx_withdrawals_external_ref'), ['external_ref'], unique=False)
        batch_op.alter_column('external_ref',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
