"""update status column

Revision ID: 5b37ca4b5130
Revises: 58da7df4f30b
Create Date: 2025-11-10 00:14:10.054976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b37ca4b5130'
down_revision = '58da7df4f30b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
