"""Update Bonus to include package_id

Revision ID: 633bbda79514
Revises: 8f0d84002ed7
Create Date: 2025-11-30 05:23:05.730680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633bbda79514'
down_revision = '8f0d84002ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bonuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'packages', ['package_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bonuses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('package_id')

    # ### end Alembic commands ###
