"""add purchase_id to Payments

Revision ID: 6c8449e9ea87
Revises: 9081432fd97c
Create Date: 2025-11-18 18:02:38.501459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8449e9ea87'
down_revision = '9081432fd97c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_id', sa.String(length=100), nullable=True))

    with op.batch_alter_table('referral_bonuses', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_payment_user_level', ['payment_id', 'user_id', 'level'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral_bonuses', schema=None) as batch_op:
        batch_op.drop_constraint('unique_payment_user_level', type_='unique')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('purchase_id')

    # ### end Alembic commands ###
