"""Fix withdrawals foreign key reference

Revision ID: 70412d0fa9dd
Revises: 215d39bf7a30
Create Date: 2025-11-10 04:14:05.922848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70412d0fa9dd'
down_revision = '215d39bf7a30'
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('withdrawals', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
#         batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

#     # ### end Alembic commands ###
   # ### end Alembic commands ###
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))  # COMMENT THIS OUT
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

 