"""Update packages columns for daily bonus atomicity

Revision ID: 8f0d84002ed7
Revises: 9dc7337fa3be
Create Date: 2025-11-29 04:37:19.762222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f0d84002ed7'
down_revision = '9dc7337fa3be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('packagecatalog_backup')
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_bonus_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('next_bonus_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('bonus_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_bonus_amount', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('total_days_paid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_bonus_locked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_column('is_bonus_locked')
        batch_op.drop_column('total_days_paid')
        batch_op.drop_column('max_bonus_amount')
        batch_op.drop_column('bonus_count')
        batch_op.drop_column('next_bonus_date')
        batch_op.drop_column('last_bonus_date')

    op.create_table('packagecatalog_backup',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reward_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bonus_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
