"""add processing_id to referralBonus

Revision ID: 9081432fd97c
Revises: 4d60f24f5a3b
Create Date: 2025-11-16 15:36:56.429889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9081432fd97c'
down_revision = '4d60f24f5a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral_bonuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_referral_bonuses_processing_id'), ['processing_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral_bonuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referral_bonuses_processing_id'))
        batch_op.drop_column('processing_id')

    # ### end Alembic commands ###
