"""add bonus and correct referrals table

Revision ID: a35b4a42e920
Revises: cae759e91328
Create Date: 2025-11-13 22:24:22.742342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35b4a42e920'
down_revision = 'cae759e91328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Referralbonuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))
        batch_op.drop_column('bonus_type')
        batch_op.drop_column('bonus_amount')

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referred_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_referrals_referred_user_id'))
        batch_op.create_index(batch_op.f('ix_referrals_referred_id'), ['referred_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('referrals_referred_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['referred_id'], ['id'])
        batch_op.drop_column('referred_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referred_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('referrals_referred_user_id_fkey'), 'users', ['referred_user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_referrals_referred_id'))
        batch_op.create_index(batch_op.f('ix_referrals_referred_user_id'), ['referred_user_id'], unique=False)
        batch_op.drop_column('referred_id')

    with op.batch_alter_table('Referralbonuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('bonus_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('amount')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
