"""add column status and column referred_id to table referrals

Revision ID: cae759e91328
Revises: d9c301eb84e4
Create Date: 2025-11-13 21:58:21.504606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cae759e91328'
down_revision = 'd9c301eb84e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Referralbonuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus_type', sa.String(length=50), nullable=True))
        batch_op.drop_column('bonua_type')

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.drop_column('completed_at')
        batch_op.drop_column('status')

    with op.batch_alter_table('Referralbonuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonua_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('bonus_type')

    # ### end Alembic commands ###
