"""ammend referralbonus and User

Revision ID: d9c301eb84e4
Revises: 3012212cc264
Create Date: 2025-11-13 15:58:59.415834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9c301eb84e4'
down_revision = '3012212cc264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Referralbonuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonua_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('referrer_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('bonus_amount', sa.Float(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'users', ['referrer_id'], ['id'])
        batch_op.drop_column('type')
        batch_op.drop_column('amount')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance_type_used', sa.String(length=20), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('available_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('referred_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referral_code_used', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('referral_bonus_eligible', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['referred_by'], ['id'])
        batch_op.drop_column('balance')

    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_balance_deducted', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('available_balance_deducted', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hold_period_applied', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.drop_column('hold_period_applied')
        batch_op.drop_column('available_balance_deducted')
        batch_op.drop_column('actual_balance_deducted')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('referral_bonus_eligible')
        batch_op.drop_column('referral_code_used')
        batch_op.drop_column('referred_by')
        batch_op.drop_column('available_balance')
        batch_op.drop_column('actual_balance')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('balance_type_used')

    with op.batch_alter_table('Referralbonuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.drop_column('bonus_amount')
        batch_op.drop_column('referrer_id')
        batch_op.drop_column('bonua_type')

    # ### end Alembic commands ###
