"""add new tables for referral networks and referralbonus

Revision ID: f02f40918248
Revises: bf86d88f2391
Create Date: 2025-11-14 15:10:13.433390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f02f40918248'
down_revision = 'bf86d88f2391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_bonus_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('bonus_percentage', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('minimum_qualifying_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('bonus_percentage >= 0 AND bonus_percentage <= 1', name='chk_bonus_range'),
    sa.CheckConstraint('level >= 1 AND level <= 20', name='chk_level_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level')
    )
    op.create_table('network_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_downline', sa.Integer(), nullable=True),
    sa.Column('active_downline', sa.Integer(), nullable=True),
    sa.Column('direct_referrals', sa.Integer(), nullable=True),
    sa.Column('network_investment', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('level_breakdown', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'snapshot_date', name='uq_daily_snapshot')
    )
    with op.batch_alter_table('network_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_snapshots_snapshot_date'), ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_snapshots_user_id'), ['user_id'], unique=False)

    op.create_table('referral_network',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ancestor_id', sa.Integer(), nullable=False),
    sa.Column('descendant_id', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('path_length', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ancestor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['descendant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ancestor_id', 'descendant_id', name='uq_network_relationship')
    )
    with op.batch_alter_table('referral_network', schema=None) as batch_op:
        batch_op.create_index('idx_network_ancestor_depth', ['ancestor_id', 'depth'], unique=False)
        batch_op.create_index('idx_network_descendant_ancestor', ['descendant_id', 'ancestor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referral_network_ancestor_id'), ['ancestor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referral_network_descendant_id'), ['descendant_id'], unique=False)

    op.create_table('referral_bonuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('referred_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('qualifying_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('bonus_percentage', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('calculated_on', sa.DateTime(), nullable=True),
    sa.Column('transaction_reference', sa.String(length=120), nullable=True),
    sa.Column('network_path', sa.String(length=500), nullable=True),
    sa.Column('is_paid_out', sa.Boolean(), nullable=True),
    sa.Column('paid_out_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('referral_bonuses', schema=None) as batch_op:
        batch_op.create_index('idx_bonus_calculated', ['calculated_on'], unique=False)
        batch_op.create_index('idx_bonus_level_payout', ['level', 'is_paid_out'], unique=False)
        batch_op.create_index(batch_op.f('ix_referral_bonuses_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referral_bonuses_referred_id'), ['referred_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referral_bonuses_transaction_reference'), ['transaction_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_referral_bonuses_user_id'), ['user_id'], unique=False)

    op.create_table('bonus_payout_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_bonus_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('next_attempt', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referral_bonus_id'], ['referral_bonuses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bonus_payout_queue', schema=None) as batch_op:
        batch_op.create_index('idx_pqueue_status_attempt', ['status', 'next_attempt'], unique=False)

    with op.batch_alter_table('Referralbonuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Referralbonuses_payment_id'))
        batch_op.drop_index(batch_op.f('ix_Referralbonuses_referred_id'))
        batch_op.drop_index(batch_op.f('ix_Referralbonuses_user_id'))

    op.drop_table('Referralbonuses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('network_depth', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('direct_referrals_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_network_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('network_total_investment', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('network_active_members', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_network_calculation', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_network_calculation')
        batch_op.drop_column('network_active_members')
        batch_op.drop_column('network_total_investment')
        batch_op.drop_column('total_network_size')
        batch_op.drop_column('direct_referrals_count')
        batch_op.drop_column('network_depth')

    op.create_table('Referralbonuses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('referred_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('referrer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('Referralbonuses_payment_id_fkey')),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], name=op.f('Referralbonuses_referred_id_fkey')),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], name=op.f('Referralbonuses_referrer_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('Referralbonuses_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Referralbonuses_pkey'))
    )
    with op.batch_alter_table('Referralbonuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Referralbonuses_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Referralbonuses_referred_id'), ['referred_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Referralbonuses_payment_id'), ['payment_id'], unique=False)

    with op.batch_alter_table('bonus_payout_queue', schema=None) as batch_op:
        batch_op.drop_index('idx_pqueue_status_attempt')

    op.drop_table('bonus_payout_queue')
    with op.batch_alter_table('referral_bonuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referral_bonuses_user_id'))
        batch_op.drop_index(batch_op.f('ix_referral_bonuses_transaction_reference'))
        batch_op.drop_index(batch_op.f('ix_referral_bonuses_referred_id'))
        batch_op.drop_index(batch_op.f('ix_referral_bonuses_payment_id'))
        batch_op.drop_index('idx_bonus_level_payout')
        batch_op.drop_index('idx_bonus_calculated')

    op.drop_table('referral_bonuses')
    with op.batch_alter_table('referral_network', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referral_network_descendant_id'))
        batch_op.drop_index(batch_op.f('ix_referral_network_ancestor_id'))
        batch_op.drop_index('idx_network_descendant_ancestor')
        batch_op.drop_index('idx_network_ancestor_depth')

    op.drop_table('referral_network')
    with op.batch_alter_table('network_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_snapshots_user_id'))
        batch_op.drop_index(batch_op.f('ix_network_snapshots_snapshot_date'))

    op.drop_table('network_snapshots')
    op.drop_table('referral_bonus_plan')
    # ### end Alembic commands ###
